### ISSUE TITLE
Website?

### ISSUE THREAD

**Issue by scith** [froodyapp/froody-server#2]
Hello,
It would be nice at some long-term point to have a web interface (or at least a landing page) :)
In the meantime, I am trying to package the app for [YunoHost](https://yunohost.org/#/) to deploy it rapidly. I will keep you in touch
Thanks

**Comment by gsantner** [comment]
@scith 
There is http://froody-app.at/ , and the facebook page https://www.facebook.com/froodyapp .
YunoHost: Feel free to do so
